### ISSUE TITLE
Substation MK3 area 

### ISSUE THREAD

**Issue by kazreth** [jimmyjon711/FactorioExtended-Plus-Power#16]
Hi

Seems the latest update (0.4.1) changed some Substation MK3 values to be identical to MK2.

I'm not sure, but I think its these values:
mk3.maximum_wire_distance = 28  [should be 42]
mk3.supply_area_distance = 14  [should be 21]

BTW - Thanks for the Mod development :-)

**Comment by cl0wnt0wn** [comment]
Upvote for awareness and prestige.
