### ISSUE TITLE
doesn't play nice with others

### ISSUE THREAD

**Issue by Bear67** [jimmyjon711/FactorioExtended-Plus-Power#17]
Error on Load after updatingto 0.4.1:
https://prntscr.com/r2lc4i

**Comment by jimmyjon711** [comment]
It looks like its because SchallOverseasRailway mod removes the collision mask just for regular big poles. 

For this to be compatible SchallOverseasRailway mod need to loop through all big-electric poles and remove the collision mask from all poles

**Comment by billbo99** [comment]
Can you please provide a copy of your "mod-list.json" ?


I copy the vanila "big-power-pole" and make some updates,  so the mk2/3 would have the same collsion mask as the mk1.

```
local mk2 = table.deepcopy(data.raw["electric-pole"]["big-electric-pole"])
mk2.name = "big-electric-pole-mk2"
mk2.icon = "__FactorioExtended-Plus-Power__/graphics/icons/" .. mk2.name .. ".png"
mk2.icon_size = 32
mk2.icon_mipmaps = nil
mk2.minable.result = mk2.name
mk2.max_health = 400
mk2.next_upgrade = "big-electric-pole-mk3"
mk2.maximum_wire_distance = 45
mk2.supply_area_distance = 2
mk2.resistances = {{type = "fire", percent = 100}}

mk2.pictures.layers[1].filename = "__FactorioExtended-Plus-Power__/graphics/entity/" .. mk2.name .. "/" .. mk2.name .. ".png"
mk2.pictures.layers[1].hr_version.filename = "__FactorioExtended-Plus-Power__/graphics/entity/" .. mk2.name .. "/hr-" .. mk2.name .. ".png"
```

I also use any existing "fast_replaceable_group" that has already been defined,  and tell the mk1 power pole that the mk2 is 
```
if not data.raw["electric-pole"]["big-electric-pole"].fast_replaceable_group then
    data.raw["electric-pole"]["big-electric-pole"].fast_replaceable_group = "big-electric-pole"
end
data.raw["electric-pole"]["big-electric-pole"].next_upgrade = "big-electric-pole-mk2"
```

As Jimmy has said the "Upgrade Planner" requires all the entites to have the same collsion mask.

**Comment by Bear67** [comment]
Here ya go @billbo99 
[mod-list.zip](https://github.com/jimmyjon711/FactorioExtended-Plus-Power/files/4208748/mod-list.zip)
