### ISSUE TITLE
mk2 bug?

### ISSUE THREAD

**Issue by bosair** [jimmyjon711/FactorioExtended-Plus-Power#25]
When a stack size is set to 100 in MK2 stack inserter, for example, it automatically changes to all inserters in the game. If you uncheck the checkbox, the value is not reset to the default 12 and remains as it was (for example, 100). This also applies to the mk2 filter manipulator.

**Comment by billbo99** [comment]
There is no code within FE+ that would updated all the inserts to have same stack size
