### ISSUE TITLE
Version 1.0.2 Incompatible with FactorioExtended Plus-CompoundSolars version 0.1.3

### ISSUE THREAD

**Issue by agomulu** [jimmyjon711/FactorioExtended-Plus-Power#27]
Updating from version 1.0.1 to 1.0.2 causes incompatibility issue with the FactorioExtended Plus-CompoundSolars mod version 0.1.3
![Capture](https://user-images.githubusercontent.com/30157664/99903351-d0ce6780-2c91-11eb-871c-ece421ed10c2.PNG)

**Comment by SirJMO** [comment]
merged dmke's 1.0 updated files, updated on the modportal and that fixed the issue I guess? Thank you dmke

**Comment by dmke** [comment]
My pleasure :-)
