### ISSUE TITLE
error since 0.17.53 with bob power and factorio extended plus 

### ISSUE THREAD

**Issue by Islandir** [jimmyjon711/FactorioExtended-Plus-Power#7]
bob power and factorio extended plus power are now failing if used together since the new update 0.17.53.
The two mods were working fine together before but now the error is:
62.296 Mods to disable:Failed to load mods: Error while running setup for entity prototype "solar-panel" (solar-panel): next_upgrade target (solar-panel-2) must have the same bounding box.

Mods to be disabled:
• bobpower
• FactorioExtended-Plus-Power

I presume this is due to the new change they made in 0.17.53:
Fixed that the game would allow entities with different sized bounding boxes or collision masks to be upgraded. (https://forums.factorio.com/72698)

I also logged the issue in bob power

**Comment by jimmyjon711** [comment]
Fixed and uploaded to mod portal, please let me know if that are any other issues. Thanks

**Comment by Islandir** [comment]
confirm that now they two mods can be loaded together. Thanks for the quick turn around.
