### ISSUE TITLE
Mod breaking Warptorio2

### ISSUE THREAD

**Issue by billbo99** [jimmyjon711/FactorioExtended-Plus-Power#9]
In your   DATA.LUA   you are changing the values for ALL accumulators.   This is breaking the mod Warptorio2.  Causing items the teleporter to be misaligned.

[https://imgur.com/a/arqUtjm](https://imgur.com/a/arqUtjm)

for _,accm in pairs(accum) do
  accm.collision_box = {{-0.7, -0.7}, {0.7, 0.7}}
  accm.fast_replaceable_group = "accumulator"
end

If I comment out the collision_box line, the mod works as expected.

Can you add some logic so that these changes are not applied if the accm.name starts with “warptorio”

**Comment by PyroFire232** [comment]
Hi, warptorio2 developer here. This for loop is not required at all, and only serves to break mods. Please remove it entirely. Your accumulator prototypes seem to be fine and use this as their collision box anyway.
